---
title: "visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document is used to test the setting of SPM model in 2d cases. 

```{r}
library(tidyverse)
library(SPM)
library(e1071)
```
```{r}
training_dat_generator <- function(r, theta, s){
  k0 <- 1
  k1 <- 1
  nlabel <- 2
  d <- 2
  seed <- 1
  rho <- c(0.5, 0.5)
  N = 100
  
  a <- 10

  S <- matrix(
    c(1, 1, 1, 1, 1, 1),
    ncol = d,
    byrow = TRUE
  )
  S <- S * s
  
  dg <- k0 + k1
  K <- nlabel * k0 + k1
  ntopic <- K
  
  Ts <- T_generator(k0, k1, nlabel)
  
  Mu <- matrix( 
    c(1, 0, r * cos(theta), r * sin(theta), 0, 0),
    ncol = d,
    byrow = TRUE
  )
  
  Lambda <- 1 / S
  Tau <- Mu * Lambda
  
  # genarate data
  set.seed(seed)
  
  dat <- document_generator_Normal(a, rho, Ts, Lambda, Tau, N, NULL, seed)
  dat
}
```
```{r}
a1 <- c()
l1 <- list()
for(i in 1:12){
  theta <- pi * i * 1 / 12
  dat <- training_dat_generator(1, theta, 0.1)
  seed <- 1
  res_VI <- SPM_training_Normal(dat[["X"]], dat[["Y"]], Ts, 0.1, c(1, 1), 0, 100, 1, 1, TRUE, nskip = nskip, seed = seed)
  prediction_VI <- SPM_predicting_Normal(dat[["X"]], res_VI[["Lambda"]], res_VI[["Mu"]], res_VI[["a"]], res_VI[["rho"]], Ts, nsample, seed, w = NULL)
  a1 <- c(a1, sum(prediction_VI[["labels"]] == dat[["Y"]]))
  print(sum(prediction_VI[["labels"]] == dat[["Y"]]))
  l1[[i]] <- res_VI
}

a2 <- c()
li2 <- list()
for(i in 1:12){
  theta <- pi * i * 1 / 12
  dat <- training_dat_generator(1, theta, 0.1)
  seed <- 1
  res_BPM_VI <- BPM_training_Normal(dat[['X']], 0.1, rep(1, 3), 0, 50, 2, 5, 3, FALSE, nchain = 1, ntrace = 1000, seed = seed)
  f2 <- svm(factor(dat[["Y"]]) ~ res_BPM_VI[["U"]])
l2 <- predict(f2, res_BPM_VI[["U"]])
print(sum(l2 == factor(dat[["Y"]])))
a2 <- c(a2, sum(l2 == factor(dat[["Y"]])))
li2[[i]] <- res_BPM_VI
}


a2
li2[[1]]$Mu
li2[[3]]$Mu
li2[[6]]$Mu
c(1, 0, r * cos(theta), r * sin(theta), 0, 0)
li2[[12]]$Mu
l1[[6]]$Mu
li2[[6]]$U
```

```{r}
# fixed
k0 <- 1
k1 <- 1
nlabel <- 2
d <- 2
seed <- 1
rho <- c(0.5, 0.5)
N = 50

# parameter
r <- 1
theta <- pi / 4

a <- 1

S <- matrix(
  c(1, 1, 1, 1, 1, 1),
  ncol = d,
  byrow = TRUE
)

S <- S * 0.01

# generated
dg <- k0 + k1
K <- nlabel * k0 + k1
ntopic <- K

Ts <- T_generator(k0, k1, nlabel)

Mu <- matrix( 
  c(1, 0, r * cos(theta), r * sin(theta), 0, 0),
  ncol = d,
  byrow = TRUE
)

Lambda <- 1 / S
Tau <- Mu * Lambda

# genarate data
set.seed(seed)

dat <- document_generator_Normal(a, rho, Ts, Lambda, Tau, N, NULL, seed)

plot_dat_2d <- function(X, Y){
  tem <- data.frame(X, factor(Y))
  colnames(tem) <- c("X1", "X2", "Y")
  p <- tem %>%
    ggplot(aes(x = X1, y = X2, color = Y)) +
    geom_point()
  print(p)
  p
}
p <- plot_dat_2d(dat$X, dat$Y)
dat <- training_dat_generator(1, pi / 2, 0.1)
plot_dat_2d(dat$X, dat$Y)
```

```{r}


N = 100





ntrace <- 2000
nchain <- 2
nskip <- 2
nsample <- 1000
```


```{r}
accuracy <- data.frame(theta = rep(pi / 12 * 1:12, 2), accuracy = c(a1, a2), method = rep(c("supervised", "unsupervised"), each = 12))
accuracy %>% ggplot(aes(x = theta, y = accuracy, color = method))  + geom_point()
 

```

